// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVPIc28sb7uUZc0VcOG6zaPu7s4uHCiMQ',
    appId: '1:625326505411:web:6df4df1fd1bf8fded71176',
    messagingSenderId: '625326505411',
    projectId: 'get-info-74d1a',
    authDomain: 'get-info-74d1a.firebaseapp.com',
    storageBucket: 'get-info-74d1a.appspot.com',
    measurementId: 'G-M5P74JVN1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFj31_1XUE7hm5Zx1aXFhZaMY276pQ5W8',
    appId: '1:625326505411:android:e0ba82fbfff28b47d71176',
    messagingSenderId: '625326505411',
    projectId: 'get-info-74d1a',
    storageBucket: 'get-info-74d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzqEvwHXriVDX2rInFi7nMpARciGvroC4',
    appId: '1:625326505411:ios:2b4c3570ed44f6add71176',
    messagingSenderId: '625326505411',
    projectId: 'get-info-74d1a',
    storageBucket: 'get-info-74d1a.appspot.com',
    iosBundleId: 'com.example.groceryStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzqEvwHXriVDX2rInFi7nMpARciGvroC4',
    appId: '1:625326505411:ios:2b4c3570ed44f6add71176',
    messagingSenderId: '625326505411',
    projectId: 'get-info-74d1a',
    storageBucket: 'get-info-74d1a.appspot.com',
    iosBundleId: 'com.example.groceryStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVPIc28sb7uUZc0VcOG6zaPu7s4uHCiMQ',
    appId: '1:625326505411:web:c22422bcefbb8af8d71176',
    messagingSenderId: '625326505411',
    projectId: 'get-info-74d1a',
    authDomain: 'get-info-74d1a.firebaseapp.com',
    storageBucket: 'get-info-74d1a.appspot.com',
    measurementId: 'G-LQM9750YMX',
  );
}
